from pathlib import Path
import pandas as pd

ROOT = Path('/home/ubuntu/upload')
out = Path('/home/ubuntu/seg_project/quantitative_petrography_results_interpretation.md')
modal = pd.read_csv(ROOT / 'modal_area_proxy_summary_by_mineral.csv')
sources = pd.read_csv(ROOT / 'modal_area_proxy_by_source.csv')
interfaces = pd.read_csv(ROOT / 'phase_interface_frequency_summary.csv')
processed = pd.read_csv(ROOT / 'processed_registered_views.csv')

mineral = modal[modal['class'] != 'Background'].copy()
source_metrics = sources[['source_id','registered_views','mineral_area_mae','mineral_composition_l1','gt_mineral_coverage','pred_mineral_coverage']].copy()
source_metrics = source_metrics.sort_values('mineral_composition_l1', ascending=False)

pivot = interfaces.pivot_table(index=['scope','class_a','class_b'], columns='map_type', values='mean_source_normalized_frequency', aggfunc='first').reset_index()
pivot['frequency_delta_prediction_minus_gt'] = pivot['ensemble_prediction'] - pivot['ground_truth']
mineral_interfaces = pivot[(pivot['scope'] == 'mineral_to_mineral_only') & (pivot['class_a'] != 'Background') & (pivot['class_b'] != 'Background')].copy()
mineral_interfaces['abs_delta'] = mineral_interfaces['frequency_delta_prediction_minus_gt'].abs()
positive = mineral_interfaces.sort_values('frequency_delta_prediction_minus_gt', ascending=False).head(6)
negative = mineral_interfaces.sort_values('frequency_delta_prediction_minus_gt', ascending=True).head(6)

lines = []
lines.append('# B7–B8 quantitative petrography: source-held test analysis')
lines.append('')
lines.append('## Data-integrity checks')
lines.append('')
lines.append(f'- Processed registered views: **{len(processed)}**.')
lines.append(f'- Independent sources: **{sources.source_id.nunique()}**.')
lines.append(f'- Views per source: **{sorted(processed.groupby("source_id").size().unique().tolist())}**; source-level aggregation is intact.')
lines.append('')
lines.append('## Mineral modal-area proxy results')
lines.append('')
lines.append(f'- Mean source-level mineral area MAE: **{sources.mineral_area_mae.mean():.4f}** (median **{sources.mineral_area_mae.median():.4f}**, range **{sources.mineral_area_mae.min():.4f}–{sources.mineral_area_mae.max():.4f}**).')
lines.append(f'- Mean source-level mineral composition L1 error: **{sources.mineral_composition_l1.mean():.4f}** (median **{sources.mineral_composition_l1.median():.4f}**, range **{sources.mineral_composition_l1.min():.4f}–{sources.mineral_composition_l1.max():.4f}**).')
lines.append('')
lines.append('| Mineral | Mean GT area | Mean predicted area | Mean signed error | Mean absolute error |')
lines.append('|---|---:|---:|---:|---:|')
for _, row in mineral.iterrows():
    lines.append(f"| {row['class']} | {row['mean_gt_area_fraction']:.4f} | {row['mean_pred_area_fraction']:.4f} | {row['mean_signed_area_error']:+.4f} | {row['mean_absolute_area_error']:.4f} |")
lines.append('')
lines.append('### Highest composition-error sources')
lines.append('')
lines.append('| Source | Mineral composition L1 | Mineral area MAE | GT mineral coverage | Predicted mineral coverage |')
lines.append('|---|---:|---:|---:|---:|')
for _, row in source_metrics.head(5).iterrows():
    lines.append(f"| {row['source_id']} | {row['mineral_composition_l1']:.4f} | {row['mineral_area_mae']:.4f} | {row['gt_mineral_coverage']:.4f} | {row['pred_mineral_coverage']:.4f} |")
lines.append('')
lines.append('## Mineral-to-mineral semantic interface frequencies')
lines.append('')
lines.append('Interface frequencies are normalized within each view and then averaged across the eight registered views per source before source-level aggregation. They quantify semantic pixel-edge interfaces, not grain contacts or 3D contact areas.')
lines.append('')
lines.append('### Most over-represented predicted mineral interfaces')
lines.append('')
lines.append('| Interface | Ground truth frequency | Prediction frequency | Prediction − GT |')
lines.append('|---|---:|---:|---:|')
for _, row in positive.iterrows():
    lines.append(f"| {row['class_a']}–{row['class_b']} | {row['ground_truth']:.4f} | {row['ensemble_prediction']:.4f} | {row['frequency_delta_prediction_minus_gt']:+.4f} |")
lines.append('')
lines.append('### Most under-represented predicted mineral interfaces')
lines.append('')
lines.append('| Interface | Ground truth frequency | Prediction frequency | Prediction − GT |')
lines.append('|---|---:|---:|---:|')
for _, row in negative.iterrows():
    lines.append(f"| {row['class_a']}–{row['class_b']} | {row['ground_truth']:.4f} | {row['ensemble_prediction']:.4f} | {row['frequency_delta_prediction_minus_gt']:+.4f} |")
lines.append('')
lines.append('## Interpretation guardrails')
lines.append('')
lines.append('- Area fractions are **two-dimensional modal-area proxies**, not bulk three-dimensional modal mineralogy.')
lines.append('- Interfaces are **semantic pixel-edge frequencies**, not verified grain-contact topology.')
lines.append('- Background remains a dataset label and is **not** interpreted as porosity.')
lines.append('- The source-held split includes 10 independent sources. These results are an informative supplementary analysis, but uncertainty should also be estimated with the repeated grouped-CV workflow before any broad geological claim is made.')

out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(out)
