"""Build the final B7-B8 Word manuscript with quantitative petrography and source-error analysis.

Prerequisites in the same scripts directory:
- build_final_b7_b8_ensemble_manuscript_self_contained.py
- build_expanded_b7_b8_ensemble_manuscript.py
- 900-DPI Figures 1-4 generated by render_expanded_context_figures_900dpi.py
- native 900-DPI strong/typical/difficult ensemble figures under --ensemble-figure-root.

All new tables are native editable Word tables. No claim of 3D modal mineralogy, grain-contact
networks, porosity, or physical units is made from the current semantic maps.
"""
from __future__ import annotations

import argparse
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor

import build_expanded_b7_b8_ensemble_manuscript as expanded

base = expanded.base
HERE = Path(__file__).resolve().parent

MODAL_ROWS = [
    ["Olivine", "0.0256", "0.0688", "+0.0432", "0.0432"],
    ["Pyroxene", "0.0540", "0.0470", "−0.0071", "0.0390"],
    ["Plagioclase", "0.1258", "0.1281", "+0.0023", "0.0539"],
    ["Alkali feldspar", "0.0742", "0.1442", "+0.0701", "0.0835"],
    ["Quartz", "0.1358", "0.0812", "−0.0546", "0.0562"],
    ["Biotite", "0.0028", "0.0180", "+0.0152", "0.0187"],
    ["Muscovite", "0.0336", "0.0143", "−0.0193", "0.0211"],
    ["Hornblende", "0.0073", "0.0096", "+0.0023", "0.0138"],
]

SOURCE_ERROR_ROWS = [
    ["Muscovite–Schist–3", "0.0866", "0.6848", "0.0856", "Quartz → alkali feldspar (19.3% of quartz); muscovite → biotite/hornblende (20.5%/20.1%)"],
    ["Pyroxene–Peridotite–1", "0.0635", "0.5369", "0.0671", "Pyroxene → olivine (71.7% of pyroxene); background → olivine (33.0% of background)"],
]

CONFUSION_ROWS = [
    ["Muscovite–Schist–3", "Quartz", "Alkali feldspar", "230,118", "0.193"],
    ["Muscovite–Schist–3", "Muscovite", "Biotite", "130,924", "0.205"],
    ["Muscovite–Schist–3", "Muscovite", "Hornblende", "128,690", "0.201"],
    ["Muscovite–Schist–3", "Quartz", "Muscovite", "128,610", "0.108"],
    ["Muscovite–Schist–3", "Quartz", "Plagioclase", "117,330", "0.099"],
    ["Pyroxene–Peridotite–1", "Pyroxene", "Olivine", "492,248", "0.717"],
    ["Pyroxene–Peridotite–1", "Background", "Olivine", "416,702", "0.330"],
    ["Pyroxene–Peridotite–1", "Olivine", "Pyroxene", "62,543", "0.093"],
    ["Pyroxene–Peridotite–1", "Pyroxene", "Plagioclase", "51,725", "0.075"],
]

INTERFACE_ROWS = [
    ["Muscovite–Schist–3", "Quartz–muscovite", "1.0000", "0.1547", "−0.8453"],
    ["Muscovite–Schist–3", "Alkali feldspar–quartz", "0.0000", "0.1787", "+0.1787"],
    ["Muscovite–Schist–3", "Muscovite–hornblende", "0.0000", "0.1176", "+0.1176"],
    ["Pyroxene–Peridotite–1", "Olivine–pyroxene", "1.0000", "0.5498", "−0.4502"],
    ["Pyroxene–Peridotite–1", "Olivine–plagioclase", "0.0000", "0.3006", "+0.3006"],
    ["Pyroxene–Peridotite–1", "Olivine–alkali feldspar", "0.0000", "0.0626", "+0.0626"],
]


def add_quantitative_methods(doc: Document) -> None:
    base.add_heading(doc, "2.8 Map-derived quantitative petrography analysis", 2)
    base.add_para(doc, "We conducted a post hoc analysis on the original 10-source held-out partition to test whether the B7–B8 semantic maps preserved source-level mineral composition and labelled phase-adjacency patterns. Each source contributed eight registered angular views; all view-level quantities were averaged within source before any summary. Angular frames were therefore not treated as independent petrographic samples.")
    base.add_para(doc, "For class c in source s, the two-dimensional mineral modal-area proxy was A_(s,c)=N_(s,c)/N_s, where N_(s,c) is the number of pixels assigned to class c and N_s is the number of analysed pixels. We report the predicted-minus-reference area difference ΔA_(s,c)=A_pred_(s,c)−A_GT_(s,c), its absolute value, and the eight-mineral source-level composition error L1_s=Σ_(c=1)^8 |ΔA_(s,c)|. These values are two-dimensional map-derived area proxies, not bulk three-dimensional modal mineralogy.")
    base.add_para(doc, "We also counted unlike four-neighbour pixel edges between mineral labels a and b. The interface count I_(s,a,b) was normalized by the total mineral-to-mineral unlike-edge count in each view, then averaged across the eight registered views of a source. This metric is explicitly termed a semantic pixel-edge interface frequency. It does not delineate individual grains, quantify physical three-dimensional contact area, or establish a grain-contact network [2,4].")


def add_quantitative_results(doc: Document) -> None:
    base.add_heading(doc, "3.6 Source-held quantitative petrography analysis", 2)
    base.add_para(doc, "The modal-area and interface analyses processed all 80 registered views from the 10 original held-out sources and then aggregated them by source. The mean source-level mineral area mean absolute error was 0.0412 (median 0.0307; range 0.0114–0.0856). Mean mineral-composition L1 error was 0.3294 (median 0.2452; range 0.0908–0.6848). The composition L1 statistic is independent of mIoU; its matching rounded mean value is coincidental and must not be interpreted as another mIoU estimate.")
    base.add_table(doc, ["Mineral", "Mean GT 2D area", "Mean predicted 2D area", "Mean signed error", "Mean absolute error"], MODAL_ROWS)
    base.add_para(doc, "Table 4. Source-held two-dimensional mineral modal-area proxies and prediction error. Fractions are averaged first within each eight-view source and then across 10 held-out sources. They are not estimates of three-dimensional bulk modal mineralogy.", italic=True)
    base.add_para(doc, "The ensemble systematically over-represented alkali feldspar (+0.0701 mean area fraction) and under-represented quartz (−0.0546). Plagioclase had near-zero mean signed bias (+0.0023), but its mean absolute error was 0.0539, demonstrating that a small aggregate bias can conceal source-specific composition error. Biotite and hornblende had low reference abundance, so their proportional errors require particular caution.")
    base.add_para(doc, "The semantic interface analysis showed that composition error also alters labelled boundary structure. At the aggregate source-held level, pyroxene–alkali feldspar and plagioclase–alkali feldspar interfaces were over-represented, whereas plagioclase–hornblende, quartz–muscovite, and alkali feldspar–hornblende interfaces were under-represented. Full matrices are provided in Appendix D; they are retained as class-boundary diagnostics and not interpreted as grain-contact topology.")


def add_source_error_results(doc: Document) -> None:
    base.add_heading(doc, "3.7 Contrasting source-specific error mechanisms", 2)
    base.add_para(doc, "Detailed analysis of two difficult held-out source/lithology cases revealed different error mechanisms. These sources were selected because they had the highest source-level mineral-composition discrepancies in the held-out analysis; the eight registered views within each source were aggregated before reporting. The comparison describes source-composition- and texture-dependent error, not independent facies replicates or a unique optical/petrogenetic mechanism.")
    base.add_table(doc, ["Source/lithology case", "Mineral mIoU", "Mineral composition L1", "Mineral area MAE", "Dominant error pathway"], SOURCE_ERROR_ROWS)
    base.add_para(doc, "Table 5. Source-specific B7–B8 error summary. mIoU excludes background. L1 is the sum of absolute error across the eight mineral 2D area proxies. Each row aggregates eight registered views into one source-level observation.", italic=True)
    base.add_para(doc, "Muscovite–Schist–3 contained reference quartz and muscovite as its only mineral labels. Quartz was frequently reassigned to alkali feldspar (19.3% of reference quartz), muscovite (10.8%), plagioclase (9.9%), background (6.8%), and hornblende (5.1%). Muscovite was frequently reassigned to biotite (20.5%), hornblende (20.1%), and plagioclase (8.0%). The true quartz–muscovite interface consequently decreased from a reference normalized frequency of 1.0000 to 0.1547 in the ensemble map, while non-reference mineral interfaces appeared.")
    base.add_para(doc, "Pyroxene–Peridotite–1 contained reference olivine and pyroxene as its only mineral labels. The dominant error was pyroxene-to-olivine reassignment: 492,248 pixels, representing 71.7% of reference pyroxene. In addition, 33.0% of reference background pixels were predicted as olivine. This created severe olivine expansion and reduced the true olivine–pyroxene semantic interface frequency from 1.0000 to 0.5498, while a non-reference olivine–plagioclase interface appeared at 0.3006.")


def add_quantitative_discussion(doc: Document) -> None:
    base.add_heading(doc, "4.8 Interpretation of map-derived petrographic quantities", 2)
    base.add_para(doc, "The quantitative petrography analysis adds information that mIoU alone cannot provide. Pixel-level segmentation accuracy and source-level mineral composition are related but not identical: a model can recover broad domains while redistributing area among mineral labels, or it can preserve approximate area while displacing boundaries. The observed alkali-feldspar over-representation and quartz under-representation demonstrate that any mineral-proportion result derived from the current model must retain class-specific uncertainty rather than be reported as a single unqualified modal estimate.")
    base.add_para(doc, "The two source-specific cases make this limitation concrete. In the muscovite-schist case, the model created multiple mineral classes absent from the reference annotation and fragmented the sole reference quartz–muscovite interface. In the pyroxene-peridotite case, the model preserved high olivine recall but substantially expanded olivine into reference pyroxene and background. These are distinct semantic failure modes: label fragmentation in one source and dominant-class expansion in the other. They should guide future data collection and model development, but they do not independently identify the responsible optical, textural, or mineral-chemical cause.")
    base.add_para(doc, "Accordingly, the present maps are appropriate for exploratory, uncertainty-aware two-dimensional mineral-domain analysis. Grain size, shape, roundness, preferred orientation, grain-contact topology, pore-network metrics, porosity, permeability, and physical area or length measurements remain outside the validated scope because they require grain-instance boundaries, scale calibration, a pore label, or independent geological/chemical reference data [2–4]. A robust next step is to repeat the composition and interface analysis inside every grouped cross-validation fold, so that derived petrographic quantities receive the same source-level uncertainty treatment as the primary segmentation metrics.")


def add_quantitative_appendix(doc: Document) -> None:
    doc.add_page_break()
    base.add_heading(doc, "Appendix C. Quantitative petrography definitions and outputs", 1)
    base.add_para(doc, "All quantitative-petrography values were generated with the fixed validation-calibrated B7 probability weight of 0.6 and B8 probability weight of 0.4 on the original held-out partition. The accompanying reproducibility package includes the source-level modal-area proxy table, predicted-versus-reference semantic-interface matrices, processed-view audit, source-specific per-class metrics, and class-transition pathways.")
    base.add_heading(doc, "Table S2. Dominant source-specific pixel misclassification pathways", 2)
    base.add_table(doc, ["Source", "Ground truth", "Predicted as", "Misclassified pixels", "Share of GT class"], CONFUSION_ROWS)
    base.add_para(doc, "Each route is aggregated across eight registered views. Percentage is the fraction of the indicated ground-truth class within that source, evaluated at 640 × 512 inference resolution.", italic=True)
    base.add_heading(doc, "Table S3. Largest source-specific mineral semantic-interface distortions", 2)
    base.add_table(doc, ["Source", "Mineral interface", "GT frequency", "Prediction frequency", "Prediction − GT"], INTERFACE_ROWS)
    base.add_para(doc, "Interface frequencies count unlike horizontal and vertical mineral-label edges, normalize by all mineral-to-mineral unlike edges within each view, and then aggregate the eight views per source. Values describe semantic pixel-edge frequencies, not individual-grain or three-dimensional contacts.", italic=True)
    base.add_heading(doc, "Appendix D. Interpretation boundaries", 1)
    base.add_para(doc, "The present 2D modal-area proxies do not establish 3D modal mineralogy. Background is a dataset label and was not interpreted as pore space. Physical dimensions were not reported because no verified micrometre-per-pixel calibration is present in the analysis manifest. Source-level interface frequencies are diagnostic of semantic class redistribution but are not grain contact networks. These restrictions are necessary for an honest translation of pixel-level segmentation into quantitative petrography.")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--context-figure-root", required=True, help="Folder containing Figure 1–4 900-DPI PNG assets.")
    p.add_argument("--ensemble-figure-root", required=True, help="Root containing native strong, typical, and difficult ensemble figures.")
    p.add_argument("--output", default="Mineral_Segmentation_Manuscript_B7_B8_Ensemble_Quantitative_Updated.docx")
    args = p.parse_args()
    context_root = Path(args.context_figure_root).resolve(); ensemble_root = Path(args.ensemble_figure_root).resolve()
    output = Path(args.output).resolve(); output.parent.mkdir(parents=True, exist_ok=True); log=[]

    doc = Document(); sec = doc.sections[0]
    sec.top_margin=Inches(.7); sec.bottom_margin=Inches(.7); sec.left_margin=Inches(.8); sec.right_margin=Inches(.8)
    doc.styles['Normal'].font.name='Arial'; doc.styles['Normal'].font.size=Pt(10)
    title=doc.add_paragraph(); title.alignment=WD_ALIGN_PARAGRAPH.CENTER; title.paragraph_format.space_after=Pt(14)
    r=title.add_run('Leakage-Safe Mineral Semantic Segmentation in Registered Polarized-Light Thin-Section Images'); r.bold=True; r.font.name='Arial'; r.font.size=Pt(18); r.font.color.rgb=RGBColor(23,63,95)
    subtitle=doc.add_paragraph(); subtitle.alignment=WD_ALIGN_PARAGRAPH.CENTER
    r=subtitle.add_run('Validation-Calibrated ResNet-34 U-Net and DeepLabV3 Ensemble with Source-Level Quantitative Petrography'); r.italic=True; r.font.name='Arial'; r.font.size=Pt(12)
    for line, italic in [('[Author names, affiliations, and corresponding-author details to be inserted before submission]',False),('Working manuscript for the Elsevier volume: Image Segmentation in the Geosciences: From Fundamentals to Frontiers',True)]:
        para=doc.add_paragraph(); para.alignment=WD_ALIGN_PARAGRAPH.CENTER; run=para.add_run(line); run.italic=italic; run.font.size=Pt(10)

    base.add_heading(doc, 'Study at a glance', 1)
    base.add_table(doc,['Independent sources','Task','Final model','Primary evidence'],[['97 thin sections / 776 registered frames','8 minerals + background','Validation-calibrated B7–B8 probability ensemble','2 × 5 grouped source-level cross-validation']])
    base.add_para(doc,'Primary grouped estimate: mineral mIoU 0.3294 ± 0.0459; mineral Dice 0.4738 ± 0.0545. Original fixed source-held test: mineral mIoU 0.2440; mineral Dice 0.3732. Supplementary source-held 2D modal-area and semantic-interface analysis: 10 independent sources / 80 registered views.',italic=True)

    abstract=base.EMBEDDED_MANUSCRIPT_SOURCES['B7_B8_Abstract_and_Introduction_Final.md'].split('# 1. Introduction',1)[0]
    base.add_markdown_body(doc,abstract)
    intro=expanded.markdown_between(expanded.EXPANDED,'## 1. Introduction: expanded version','## 2.7 Mathematical'); base.add_markdown_body(doc,'# 1. Introduction\n'+intro)
    expanded.add_figure(doc,expanded.exact(context_root,'Figure_1_dataset_construction_900dpi.png'),'Figure 1. Dataset construction and source-level study design. Real registered polarized-light views from a thin section share one indexed semantic mask. All eight views were retained in one source-level partition; no angular view from a test source entered training or validation. Dataset [1]; this study.',log)
    expanded.add_figure(doc,expanded.exact(context_root,'Figure_2_representative_mineral_gallery_900dpi.png'),'Figure 2. Representative registered mineral-image and semantic-mask gallery. Each pair shows a real source image and its corresponding semantic mask. Sources were selected to illustrate observed mineral, lithological, and optical diversity, not to estimate class frequency or showcase model performance. Dataset [1]; this study.',log)

    method_all=base.EMBEDDED_MANUSCRIPT_SOURCES['B7_B8_Methodology_and_Results_Final.md']; methods=method_all.split('# 3. Results',1)[0]; base.add_markdown_body(doc,methods,citation_remap=True)
    mathematics=expanded.markdown_between(expanded.EXPANDED,'## 2.7 Mathematical formulation','## 4. Discussion'); mathematics='## 2.7 Mathematical formulation of the source-level segmentation and ensemble protocol\n'+mathematics.split('\n',1)[1]; base.add_markdown_body(doc,mathematics)
    add_quantitative_methods(doc)
    expanded.add_figure(doc,expanded.exact(context_root,'Figure_3_B7_B8_ensemble_framework_900dpi.png'),'Figure 3. B7–B8 probability ensemble and validation-only selection. B7 and B8 were trained under the same leakage-safe source-level protocol, their probabilities were fused, and the coefficient was selected only on validation sources. Architecture foundations [7,8]; this study.',log)

    results='# 3. Results\n'+method_all.split('# 3. Results',1)[1].split('# References',1)[0]; results=results.replace('Figures 3–5','Figures 5–7'); base.add_markdown_body(doc,results,citation_remap=True)
    add_quantitative_results(doc); add_source_error_results(doc)
    expanded.add_figure(doc,expanded.exact(context_root,'Figure_4_grouped_validation_evidence_900dpi.png'),'Figure 4. Model-development progression and grouped source-level validation. The original fixed source-held test documents final ensemble selection, whereas the repeated grouped source-level cross-validation summary is the primary performance estimate. Error statistics were computed from ten held-out source-level fold estimates; this study.',log)
    expanded.add_figure(doc,expanded.find(ensemble_root,['strong']),'Figure 5. Strong native-resolution B7–B8 ensemble predictions. Each triplet presents the polarized-light input, semantic ground truth, and ensemble prediction. The favourable examples are retained as illustrations and are not the primary accuracy claim.',log)
    expanded.add_figure(doc,expanded.find(ensemble_root,['typical']),'Figure 6. Typical native-resolution B7–B8 ensemble predictions. Broad mineral domains are often recovered, while local mineral-identity confusion and boundary error remain visible.',log)
    expanded.add_figure(doc,expanded.find(ensemble_root,['hard']),'Figure 7. Difficult native-resolution B7–B8 ensemble predictions. These cases expose rare-phase and source-composition failure modes rather than selectively reporting favourable examples.',log)

    discussion=expanded.markdown_between(expanded.EXPANDED,'## 4. Discussion: expanded version','## Table S1'); base.add_markdown_body(doc,'# 4. Discussion\n'+discussion); add_quantitative_discussion(doc)
    table_s1=expanded.markdown_between(expanded.EXPANDED,'## Table S1.','## References'); base.add_markdown_body(doc,'# Table S1.'+table_s1)
    expanded.add_endmatter(doc); add_quantitative_appendix(doc)
    doc.save(output); output.with_suffix('.figure_insertion_log.txt').write_text('\n'.join(log)+'\n',encoding='utf-8'); print(output); print(output.with_suffix('.figure_insertion_log.txt'))

if __name__=='__main__':
    main()
